#!/bin/bash
#
# This is the runsim for leaf (testcase) directories.

source ../lab2-program/scripts/runsim-master.sh

run-vcs \
    ./testbench.sv \
    ./testcase.sv \
    ./ram.v \
    +plusarg_save +ntb_random_seed_automatic

