#!/bin/bash
#
# This is the runsim for leaf (testcase) directories.

source ../../scripts/runsim-master.sh

run-vcs \
    ../../testbench/testbench.sv \
    ../../rtl/counter_fixed.v \
    ./testcase.sv \
    +plusarg_save +ntb_random_seed_automatic

