#!/bin/bash
#
# This is the runsim for leaf (testcase) directories.

source ../../scripts/runsim-master.sh

run-vcs \
    ../../testbench/memory_tb.sv \
    ../../testbench/memory_interface.sv \
    ../../rtl/memory_core.sv \
    ../../rtl/memory_ctrl.sv \
    testcase.sv \
    +plusarg_save +ntb_random_seed_automatic

