#!/bin/bash
#
# This is the runsim for leaf (testcase) directories.

source ../../scripts/runsim-master.sh

run-vcs \
    ../../testbench/testbench.sv \
    ../../rtl/switch.sv \
    ../../rtl/switch_interface.sv \
    testcase.sv \
    +plusarg_save +ntb_random_seed_automatic

