#!/bin/bash

run-full-vcs ()
{
    echo "run-full-vcs: $@"
    qsub -I -q o_pri_interactive_vcs_.4G $VCS/bin/vcs \
         -R -l vlog.log \
         -debug_pp \
         -sverilog \
         $@
}


run-full-vcs \
    testbench.sv \
    counter.v \
    scenarios/counter_disable_count/testcase.sv

